### ISSUE TITLE
Why the fuck isn't this done yet

### ISSUE THREAD

**Issue by stevester94** [EvanSooHoo/CarbCounter#1]
**See title, Thanks :)**

**Comment by EvanSooHoo** [comment]
@stevester94 Thank you for opening an issue!  I am working to finish CarbCounter as soon as I can, but things have been fairly busy at work.  Thank you for your continued patience, and thank you for your interest in CarbCounter!

tl;dr cant figure out how to make the most basic kotlin room functions work

will close issue when done

**Comment by EvanSooHoo** [comment]
Update: Gradle files had to be revised to compile like the app had before.  App now immediately crashes on a run.  Stacktrace isn't helpful; run error is mysterious.  At this point in time, "CarbCounterPublic" probably has a better chance of succeeding because that at least will run

**Comment by EvanSooHoo** [comment]
Update: CarbCounterPublic now gets the mystersterious crash as well.  The issue here, at least, was isolated to adding in the xml for button placement and recyclerview.  

Possible causes: 

*Incorrect versions specified in build.gradle files
*Improper usage of FloatingActionButton
*Choice of deprecated emulator, perhaps a series of software updates are in order

**Comment by EvanSooHoo** [comment]
Update: The mysterious run issue remains an issue.  More possible causes:

*NDK Version resolution.  NDK has been updated and I have used some of the top fixes for this, but nothing seems to have worked.  I have also updated all Android Studio software
*AVD configuration
*ANDROID_SDK_ROOT

These are all possible avenues to explore.  As of now, the project still crashes immediately without any sort of user interaction or error

**Comment by stevester94** [comment]
I don't want excuses, I want results. You know how much money I'm losing every second this isn't done? Thousands, thousands of dollars.

**Comment by EvanSooHoo** [comment]
Sir, with all due respect, both teams are working around the clock to resolve this issue.  The CarbCounterPublic team made a breakthrough tonight, and fixed their problem by adding in dependencies for FloatingActionButton.  But the fix still did not suffice for CarbCounter, likely because the Support library was deprecated in favor of the material library.

I do not know what any of these things mean.  All I know is that software that worked before is suddenly "dangerous legacy" as of this week.  Next week, is the material library going to be replaced by the materialXSupremeMasterCard library?

Tomorrow morning, both teams will convene to seriously consider whether our choice to use google was a mistake

**Comment by EvanSooHoo** [comment]
BREAKTHROUGH!!!!!!1111

*******This morning, our team discovered that by simply adding

android.useAndroidX = true
android.enableJetifier = false

to gradle.properties, constantly building and rebuilding, changing target sdk version to 28, and adding implementation 'com.google.android.material:material:1.0.0-alpha1' (not compile, obviously, because compile would break) to dependencies in build.gradle (build.gradle is not to be confused with the other build.gradle, because that would be a rookie mistake), they were able to get PAST the issue they were having!!!!

Granted, the app still immediately crashes when you hit the play button due to some runtime issue with constraintlayout, but that's WAAAAY beyond where it got before because of the issue with the new material library.  With any luck, we may be able to restore the app to the point where it crashes when you hit the save button, like it had six months ago!!!!

**Comment by EvanSooHoo** [comment]
UPDATE: The issue was actually with constraintlayout.  

When migrating to androidx, activity_main.xml has to be modified so that it uses

androidx.constraintlayout.widget.ConstraintLayout

and

androidx.constraintlayout.widget.Guideline

**Comment by EvanSooHoo** [comment]
UPDATE: Database seems to be working

**Comment by EvanSooHoo** [comment]
EMERGENCY: CarbCounter is down and currently under maintenance.  A description follows - 

TODAY, on a Sunday around 5PM, one of our more careless engineers attempted to carry out the very reckless and extremely irresponsible act of changing the database from storing an int to storing a string.  The app was working perfectly, but in his insanely reckless work, this engineer neglected to realize that such a drastic change requires the obvious step of updating the database version and carrying out a room migration.  Such actions are clearly detailed here, which contains a very short and simple series of steps to perform if one wishes to change the database schema

https://medium.com/androiddevelopers/understanding-migrations-with-room-f01e04b07929

Fortunately, this engineer has been terminated and the rest of the team has been called on to work tonight on restoring this system to its former glory

**Comment by EvanSooHoo** [comment]
UPDATE: CRISIS AVERTED.  

One of our more resourceful engineers discovered a fix involving a delete of some cached memory, but we sincerely apologize for the inconvenience the aforementioned engineer's actions have caused you.  In his hubris, he believed that changing a database from using int to using a string was as simple as calling toString.  Clearly he misunderstood the complexity and depth of such a fundamental modification to the database schema.

You will be happy to know that his termination consists of no severance package.

**Comment by EvanSooHoo** [comment]
UPDATE: App is READY TO SHIP, with one small caveat: You can only view the database results by plugging it into a computer.  You will need android studio to view the contents of the database.

Seems like a pretty minor inconvenience to me, but both teams are now busy at work implementing a feature in which the user can see the database results in something called a recyclerview.

No idea what that means, but it sounds much more ecofriendly than a listview.

**Comment by EvanSooHoo** [comment]
Our team has finally released version 1.0
